### ISSUE TITLE
Preview works but Live refused to work

### ISSUE THREAD

**Issue by Reg11o** [TzuHuanTai/Pi-Camera#3]
After following the standard instructions listed on the main page and added `--no_audio` to solve an ADM-raised error, and `--hw_accel` for better performance on zero 2 w, I did get the preview working.
![image](https://github.com/user-attachments/assets/137ab70d-2bf0-479f-85a8-b2e70310cb6c)
But when I go to Live and hit the play button, it turns into the broadcast icon for a while, did nothing and showed the play button again. 
![image](https://github.com/user-attachments/assets/dba68c91-5722-4776-b0b3-75194235d0aa)
![image](https://github.com/user-attachments/assets/84b16a8b-05e2-4c65-8b36-76b9d63bd0fd)
Any possible solution for this situation? Thanks!

**Comment by TzuHuanTai** [comment]
Which browser/os are you using? And what is your full args for `pi_webrtc`? We need more info to figure it out. The preview and video page use the same webrtc code to build the connection. I think the issue might be the video transmission. 
BTW, the default timeout is set to 10 second only, if so, it'll force stop connecting.

**Comment by Reg11o** [comment]
> Which browser/os are you using? And what is your args for pi_webrtc? We need more info to figure it out. The preview and video page use the same webrtc code to build the connection. I think the issue might be the video transmission. BTW, the default timeout is set to 10 second only, if so, it'll force stop connecting.

I'm using Brave v1.73.89 with the Brave shield OFF, on Windows 10 22h2. The args would look something like this:
`./pi_webrtc --use_libcamera --fps=30 --width=1280 --height=720 --no_audio --hw_accel --mqtt_host=c[REDACTED]db1c5974887090a72.s1.eu.hivemq.cloud --mqtt_port=8883 --mqtt_username=railvisioncams --mqtt_password=[REDACTED] --uid=38ff76c4-[REDACTED]`

**Comment by TzuHuanTai** [comment]
I just tried, I can watch live stream on Windows 10 Brave v1.73.89 by using my pi zero2 with the same args.
And I noticed the video connection will be blocked if not allow media permissions.
![image](https://github.com/user-attachments/assets/973e6e99-c92d-4799-9de6-528af0a5e360)

**Comment by Reg11o** [comment]
> I just tried, I can watch live stream on Windows 10 Brave v1.73.89 by using my pi zero2 with the same args. And I noticed the video connection will be blocked if not allow media permissions. ![image](https://private-user-images.githubusercontent.com/35286773/386991385-973e6e99-c92d-4799-9de6-528af0a5e360.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzA5MzAsIm5iZiI6MTczMTg3MDYzMCwicGF0aCI6Ii8zNTI4Njc3My8zODY5OTEzODUtOTczZTZlOTktYzkyZC00Nzk5LTlkZTYtNTI4YWYwYTVlMzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDE5MTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4OWZkYjZlZWEyODZjM2RiZWI2YjNjM2FmOTNjMTRhODQ4OTNjMjQ3MzQzN2YzZWJkYmVkNTE5YmQxZjI3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aUuf1vSsskSa0mO44JQGHcYNpvKVfaCY-6an1k_BHcM)

Thank you so much for that, I've allowed microphone permission on my browser and although that permission request seemed unrelated, it did allow the stream to work.
![image](https://github.com/user-attachments/assets/06d88270-c34c-4b25-8576-6454fa62a74a)
Appreciate your time and effort to solve this problem for me, thank you!

**Comment by TzuHuanTai** [comment]
Unless you turn off the mic and speaker before clicking the play button.
![image](https://github.com/user-attachments/assets/7f8561f1-a138-477c-874a-2e953b13598d)

**Comment by Reg11o** [comment]
> Owner

I did it still didn't make the stream show up. Somehow allowing the perm solved all things for me.
By the way, any ways that I can autorun the args at startup for the pi? I tried to put the args on the second last line of `/etc/rc.local` but it did nothing as well.

**Comment by TzuHuanTai** [comment]
Please follow the instructions `run as the Linux service` in the wiki page [here](https://github.com/TzuHuanTai/RaspberryPi-WebRTC/wiki/Advanced-Settings#run-as-linux-service).
You can skip pulseaudio settings.
